"""
Audit Controller & FastAPI Router
=================================
Provides real-time access to the immutable cryptographic audit trail store
generated by the HALO pipeline (FR-14 / PRD Section 52).
Reads 100% live data directly from audit_store.jsonl.
"""

import os
import json
import hashlib
from typing import Dict, List, Any, Optional
from datetime import datetime

from fastapi import APIRouter, HTTPException, Query, status
from pydantic import BaseModel, Field

router = APIRouter(prefix="/audit", tags=["audit"])


def _find_audit_log_path() -> str:
    """Locates audit_store.jsonl across common execution root directories."""
    candidates = [
        os.path.abspath("audit_store.jsonl"),
        os.path.abspath("backend/audit_store.jsonl"),
        os.path.abspath("../backend/audit_store.jsonl"),
        os.path.abspath("../audit_store.jsonl"),
        os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "audit_store.jsonl"),
    ]
    for p in candidates:
        if os.path.exists(p) and os.path.getsize(p) > 0:
            return p
    # Fallback to the largest candidate if any exists
    existing = [p for p in candidates if os.path.exists(p)]
    if existing:
        return max(existing, key=os.path.getsize)
    return os.path.abspath("audit_store.jsonl")


def _read_all_records() -> List[Dict[str, Any]]:
    """Reads raw JSONL records from the live audit store."""
    path = _find_audit_log_path()
    records = []
    if not os.path.exists(path):
        return []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
                records.append(rec)
            except Exception:
                continue
    # Reverse so newest are first
    records.reverse()
    return records


def _verify_content_hash(record: Dict[str, Any]) -> bool:
    """Recomputes SHA-256 of payload without content_hash to verify tamper-proof integrity."""
    stored_hash = record.get("content_hash", "")
    if not stored_hash:
        return False
    payload = {k: v for k, v in record.items() if k != "content_hash"}
    serialized = json.dumps(payload, sort_keys=True, ensure_ascii=False)
    computed = hashlib.sha256(serialized.encode("utf-8")).hexdigest()
    return computed == stored_hash


# ─── Pydantic Schemas ─────────────────────────────────────────────────────────

class AuditItemSummary(BaseModel):
    audit_id: str
    timestamp: str
    query: str
    claims_count: int
    supported_claims_count: int
    fail_closed: bool
    overall_confidence: float
    content_hash: str
    hash_valid: bool
    verdict_accepted: bool


class AuditMetrics(BaseModel):
    total_audits: int
    total_claims_audited: int
    average_confidence: float
    fail_closed_rate: float
    integrity_verified_count: int
    log_file_path: str
    log_file_size_bytes: int


class AuditListResponse(BaseModel):
    total: int
    metrics: AuditMetrics
    records: List[AuditItemSummary]


# ─── Endpoints ────────────────────────────────────────────────────────────────

@router.get("/logs", response_model=AuditListResponse)
def list_audit_logs(
    search: Optional[str] = None,
    fail_closed_only: Optional[bool] = None,
    limit: int = 50,
    offset: int = 0,
):
    """
    Returns live cryptographic audit events directly from audit_store.jsonl.
    Zero mock data — 100% immutable pipeline records.
    """
    all_records = _read_all_records()
    filtered = []

    # Clean up FastAPI Query objects if invoked directly
    search_str = search if isinstance(search, str) else None
    fc_val = fail_closed_only if isinstance(fail_closed_only, bool) else None

    for r in all_records:
        aid = r.get("audit_id", "")
        q = r.get("query", "")
        verdict = r.get("verdict") or {}
        fc = verdict.get("fail_closed", False)

        if search_str:
            s_low = search_str.lower()
            if s_low not in aid.lower() and s_low not in q.lower():
                continue

        if fc_val is not None and fc != fc_val:
            continue

        filtered.append(r)

    # Compute live metrics across all records
    tot = len(all_records)
    total_claims = sum(len(r.get("claims", [])) for r in all_records)
    conf_scores = [
        float((r.get("confidence") or {}).get("overall_confidence", 0.0))
        for r in all_records
    ]
    avg_conf = sum(conf_scores) / tot if tot > 0 else 0.0
    fc_count = sum(1 for r in all_records if (r.get("verdict") or {}).get("fail_closed", False))
    fc_rate = (fc_count / tot * 100.0) if tot > 0 else 0.0

    valid_hashes = sum(1 for r in all_records if _verify_content_hash(r))

    log_path = _find_audit_log_path()
    file_size = os.path.getsize(log_path) if os.path.exists(log_path) else 0

    metrics = AuditMetrics(
        total_audits=tot,
        total_claims_audited=total_claims,
        average_confidence=round(avg_conf, 3),
        fail_closed_rate=round(fc_rate, 1),
        integrity_verified_count=valid_hashes,
        log_file_path=os.path.basename(log_path),
        log_file_size_bytes=file_size,
    )

    # Slice for pagination
    sliced = filtered[offset : offset + limit]

    summaries = []
    for r in sliced:
        claims = r.get("claims", [])
        verifications = r.get("verifications", [])
        sup_count = sum(1 for v in verifications if v.get("status") == "SUPPORTED")
        verdict = r.get("verdict") or {}
        conf = r.get("confidence") or {}

        summaries.append(
            AuditItemSummary(
                audit_id=r.get("audit_id", ""),
                timestamp=r.get("timestamp", ""),
                query=r.get("query", ""),
                claims_count=len(claims),
                supported_claims_count=sup_count,
                fail_closed=bool(verdict.get("fail_closed", False)),
                overall_confidence=round(float(conf.get("overall_confidence", 0.0)), 2),
                content_hash=r.get("content_hash", ""),
                hash_valid=_verify_content_hash(r),
                verdict_accepted=bool(verdict.get("is_accepted", True)),
            )
        )

    return AuditListResponse(
        total=len(filtered),
        metrics=metrics,
        records=summaries,
    )


@router.get("/logs/{audit_id}")
def get_audit_record_detail(audit_id: str):
    """
    Returns full raw audit record including neural-symbolic check results,
    exact citation matches, per-claim confidence scores, and SHA-256 integrity seal.
    """
    all_records = _read_all_records()
    for r in all_records:
        if r.get("audit_id") == audit_id:
            record_copy = dict(r)
            record_copy["hash_valid"] = _verify_content_hash(r)
            return record_copy

    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Audit record '{audit_id}' not found in audit store.",
    )
